name: Python application
on:
  push:
    branches: [ main ]
    path-ignore:
      - 'README.md'
    
    pull_request:
      branches: [ main ]
      paths-ignore:
        - 'README.md'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest tox
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest
      run: pytest -v

    - name: tox
      run: tox