# GitHub Actions workflow to upload a Python package to PyPI when a release is published

name: Upload Python Package

on:
  release:
    types: [published] # Trigger workflow when a release is published

permissions:
  contents: read # Only read access to repository contents

jobs:
  deploy:

    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v3 # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v3 # Set up Python environment
      with:
        python-version: '3.8' # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip # Upgrade pip
        pip install flake8 pytest           # Install linting and testing tools
        pip install -r requirements.txt     # Install project dependencies
        pip install build                   # Install build tool

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest -v    # Run tests with verbose output

    - name: Build package
      run: python -m build # Build the Python package

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29 # Publish to PyPI
      with:
        user: __token__ # Use PyPI token authentication
        password: ${{ secrets.PYPI_API_TOKEN }} # PyPI API token stored in GitHub secrets